### PR TITLE
Added Useless Error Detector and associated tests

### PR DESCRIPTION
**Pull request by malawadd**
this detector detects errors that arent used, solodit link for the issue.

https://solodit.xyz/issues/unused-pausableupgradeablecannotrenouncewhilepaused-error-should-be-removed-cyfrin-none-cyfrin-wormhole-evm-ntt-v2-markdown

### CODE REVIEW

**Comment by TilakMaddy** [comment]
Names of identifiers may not always be unique. So try using IDs : )

**Comment by malawadd** [comment]
> Names of identifiers may not always be unique. So try using IDs : )

any example of it , because i would need to test it

**Comment by TilakMaddy** [comment]
https://docs.cyfrin.io/aderyn-custom-detectors/testing-your-detector Read this example in the docs

**Comment by malawadd** [comment]
> https://docs.cyfrin.io/aderyn-custom-detectors/testing-your-detector Read this example in the docs
> 
> The `.id` property on the modifier is used to check if we are referencing the same modifier : )

bear with me here a little bit please hahahha, Im not sure I understood what you meant by "Names of identifiers may not always be unique", because solidity wont even allow you to compile if modifiers or errors have the same name. so in what case will referencing identifiers by name will cause them to fail ? or are we talking about aderyn itself here?

**Comment by TilakMaddy** [comment]
> > https://docs.cyfrin.io/aderyn-custom-detectors/testing-your-detector Read this example in the docs
> > The `.id` property on the modifier is used to check if we are referencing the same modifier : )
> 
> bear with me here a little bit please hahahha, Im not sure I understood what you meant by "Names of identifiers may not always be unique", because solidity wont even allow you to compile if modifiers or errors have the same name. so in what case will referencing identifiers by name will cause them to fail ? or are we talking about aderyn itself here?

`context` contains variable names, identifiers, modifiers, etc from all files in the compilation group. That's why id is the real differentiator. Try adding more solidity files with same error name, identifier name, etc and you will see it first hand : )

**Comment by malawadd** [comment]
> `context` contains variable names, identifiers, modifiers, etc from all files in the compilation group. That's why id is the real differentiator.

oh you're actually correct , so how do I update this ?

**Comment by TilakMaddy** [comment]
Now it's looking good! Thanks for the submission : )

**Comment by TilakMaddy** [comment]
https://github.com/Cyfrin/aderyn/pull/372#issuecomment-2079017867

 Can you also complete the following steps as Alex has pointed out here ?

**Comment by malawadd** [comment]
> [#372 (comment)](https://github.com/Cyfrin/aderyn/pull/372#issuecomment-2079017867)
> 
> Can you also complete the following steps as Alex has pointed out here ?

What are those for, all tests are passing in this pr?

**Comment by TilakMaddy** [comment]
> > [#372 (comment)](https://github.com/Cyfrin/aderyn/pull/372#issuecomment-2079017867)
> > Can you also complete the following steps as Alex has pointed out here ?
> 
> What are those for, all tests are passing in this pr?

You can think of those steps as the final formalities before merge. Basically they generate some stuff required to make CI happy : )

**Comment by malawadd** [comment]
> > > [#372 (comment)](https://github.com/Cyfrin/aderyn/pull/372#issuecomment-2079017867)
> > > Can you also complete the following steps as Alex has pointed out here ?
> > 
> > 
> > What are those for, all tests are passing in this pr?
> 
> You can think of those steps as the final formalities before merge. Basically they generate some stuff required to make CI happy : )

I see but where is CI complaining right? Or how will it complain? I'm trying to understand how the process works hahaha, that's why I'm asking a lot of questions, and thank you so much for answering them. I super appreciate you.

**Comment by malawadd** [comment]
okay , it was complaining i dont have the report files, i added those after running clippy and reportgen.

**Comment by malawadd** [comment]
hopefully no complains now i ran the steps in https://github.com/Cyfrin/aderyn/pull/372#issuecomment-2079017867 few times and so far no files changed after this final push

**Comment by alexroan** [comment]
Hey there, thank you so much for the submission!

Good news: this PR has been accepted as a valid submission. 🥳 

Once the hackathon has concluded, we'll review, polish, and hopefully merge the submissions - whereby this one will be considered for a prize :)

**Review by alexroan — APPROVED** [review]
Accepted for a reward!

Tests will be fixed in the `dev-hackathon` branch.

**Comment by malawadd** [comment]
> Accepted for a reward!
> 
> Tests will be fixed in the `dev-hackathon` branch.

thats great to hear thank you so much

**Pull request merged**
