### PR TITLE
Fix: JSON output misspelled `medium_issue` -> `medium_issues`

### PR DESCRIPTION
**Pull request by TilakMaddy**
.

(for homogeneity)

### CODE REVIEW

**Review by alexroan — APPROVED** [review]

**Comment by alexroan** [comment]
Ready to merge once conflicts are resolved @TilakMaddy !

**Comment by TilakMaddy** [comment]
@alexroan You can merge this now

**Comment by alexroan** [comment]
Sorry, @TilakMaddy ! I've merged another PR before checking this 🤦 

Please run again and DM me once it's ready and I'll try to get in ASAP

**Comment by TilakMaddy** [comment]
No problem Alex :)

**Review by alexroan — APPROVED** [review]

**Pull request merged**
