### PR TITLE
Upgrade foundry-config to latest version

### LINKED ISSUE #526: Use the latest foundry-config and foundry-compilers
Run `aderyn` on this first flight

https://github.com/Cyfrin/2024-06-Dussehra

```
thread 'main' panicked at /Users/tilakmadichetti/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foundry-config-0.2.0/src/lib.rs:466:55:
failed to extract foundry config:
foundry config error: Unknown evm version: cancun for setting `evm_version`

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by alexroan**
[foundry-config](https://crates.io/crates/foundry-config) is not, so we must use [cyfrin-foundry-config](https://crates.io/crates/cyfrin-foundry-config) v0.2.0

Fixes #526

### CODE REVIEW

**Comment by alexroan** [comment]
@TilakMaddy The changes that we inherit from the latest foundry packages alter the flow of the ICF.
I've resolved the dependency mismatches, but changing anything further probably requires a deep dive into the Foundry compilation flow, which you have more experience with.

Could you lend a hand and take a look at this branch, please?

**Comment by TilakMaddy** [comment]
@alexroan I think we must only focus on `cyfrin-foundry-config`. I am aware that `foundry-compilers` has changed quite a bit but I don't see a strong reason to update aderyn's dependency on it. We're only relying on graph resolution and it's working fine (given that it's quite unstable and chances are the moment we update, they change it again... I think we should wait)

**Comment by alexroan** [comment]
OK, good context.

> The latest foundry-config does not need latest foundry-compilers. They are not interdependent anywhere in our architecture (nor should they) :)

@TilakMaddy I believe they are reliant, I had some conflicting structs initially, hence why I then updated both of them.
I'll revert the foundry-compilers change to demonstrate the issue.

**Comment by alexroan** [comment]
`RelativeRemapping` is the dependency that is clashing rn @TilakMaddy :

```
error[E0308]: mismatched types
   --> aderyn_driver/src/config_helpers.rs:303:34
    |
303 |         config.remappings = vec![rel_remap];
    |                                  ^^^^^^^^^ expected `RelativeRemapping`, found a different `RelativeRemapping`
    |
    = note: `RelativeRemapping` and `RelativeRemapping` have similar names, but are actually distinct types
note: `RelativeRemapping` is defined in crate `cyfrin_foundry_compilers`
   --> /Users/alexroan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cyfrin-foundry-compilers-0.3.20-aderyn/src/remappings.rs:289:1
    |
289 | pub struct RelativeRemapping {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: `RelativeRemapping` is defined in crate `foundry_compilers_artifacts_solc`
   --> /Users/alexroan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foundry-compilers-artifacts-solc-0.8.0/src/remappings.rs:285:1
    |
285 | pub struct RelativeRemapping {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by alexroan** [comment]
@TilakMaddy I actually resolved this issue by making the remappings that the `cyfrin_foundry_config` crate uses, public: https://github.com/Cyfrin/foundry/pull/1

This way, we can use _that_ version instead of our own from the `cyfrin_foundry_compilers`, and it works! :D

**Comment by alexroan** [comment]
@TilakMaddy please review this and approve it if you think it resolves #526 :)

**Comment by TilakMaddy** [comment]
> @TilakMaddy please review this and approve it if you think it resolves #526 :)

Sure 🙂

**Comment by TilakMaddy** [comment]
Side note - I'm getting this error to update rust
```
error: package `cyfrin-foundry-config v0.2.1` cannot be built because it requires rustc 1.79 or newer, while the currently active rustc version is 1.77.2
Either upgrade to rustc 1.79 or newer, or use
cargo update cyfrin-foundry-config@0.2.1 --precise ver
where `ver` is the latest version of `cyfrin-foundry-config` supporting rustc 1.77.2
```

**Comment by TilakMaddy** [comment]
#526  is resolved :)

**Review by TilakMaddy — APPROVED** [review]
LGTM!

**Pull request merged**
