### PR TITLE
division_before_multiplication

### PR DESCRIPTION
**Pull request by scab24**
New detector tasked with verifying if there are divisions before multiplications in the code

### CODE REVIEW

**Comment by alexroan** [comment]
Hey @scab24 !

Thank you for the submission! :)

To resolve these CI errors, try the following commands:

1. `cargo clippy` or `cargo clippy --fix`
2. `cargo fmt`
3. `./cli/reportgen.sh` (this regenerates the reports)

**Comment by scab24** [comment]
> Hey @scab24 !
> 
> Thank you for the submission! :)
> 
> To resolve these CI errors, try the following commands:
> 
> 1. `cargo clippy` or `cargo clippy --fix`
> 2. `cargo fmt`
> 3. `./cli/reportgen.sh` (this regenerates the reports)

Perfect, I've made the changes. Would it be correct now?

**Comment by alexroan** [comment]
> > Hey @scab24 !
> > Thank you for the submission! :)
> > To resolve these CI errors, try the following commands:
> > 
> > 1. `cargo clippy` or `cargo clippy --fix`
> > 2. `cargo fmt`
> > 3. `./cli/reportgen.sh` (this regenerates the reports)
> 
> Perfect, I've made the changes. Would it be correct now?

It looks as though you're still getting some clippy errors with unused imports https://github.com/Cyfrin/aderyn/actions/runs/8849278684/job/24301425931?pr=372

**Comment by TilakMaddy** [comment]
Some tests here are failing but that looks more like an issue from aderyn's side. Some tests rely on names of temporary json files which care susceptible to be overridden on new compilations

I think so far it's good : )

**Comment by scab24** [comment]
> Hey there, thank you so much for the submission!
> 
> Good news: this PR has been accepted as a valid submission. 🥳
> 
> Once the hackathon has concluded, we'll review, polish, and hopefully merge the submissions - whereby this one will be considered for a prize :)

Great, I'll try to develop many more detectors !

You have a very good and friendly team, Tilak has helped me a lot

**Review by alexroan — APPROVED** [review]
Accepted for a reward!

Tests will be fixed in the `dev-hackathon` branch.

**Pull request merged**
